### ISSUE TITLE
Seems can not parse right?

### ISSUE THREAD

**Issue by KECB** [larryzhuo/JavaMinicap#1]
I'm also trying to solve the huge CPU usage problem. 
But by using your parser class, I cannot parse any image. Even using your whole project, it's just showed a black image. Is there something I missed?

**Comment by larryzhuo** [comment]
it base the openstf mincap lib.  did you put it into phone

**Comment by KECB** [comment]
Yes, already put them on the phone. 
The confusing part is when you call this method:

```
public BufferedImage getFrame(){
		return this.bi1;
}
```
Is the image would change?

**Comment by KECB** [comment]
It seems has some error when I try to execute 
```
Util.runCommand(Util.ADB+" -s "+this.serial+" shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -P 1080x1920@"+MainDemo.AREA_WIDTH+"x"+MainDemo.AREA_HEIGHT+"/0");
```

**Comment by KECB** [comment]
I'm running the command manually on the terminal. It works now. 
But still don't understand why this crushed.

**Comment by larryzhuo** [comment]
the code is short, i think you can read it and understand it.  it just parse the stream read from minicap base minicap protocal definition.  i change some code recently but have't upload to github. will do laterly

**Comment by KECB** [comment]
Thanks a lot. I think it just about thread block. Try to use new thread, then it works.
